name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./src   # ensures src is available for imports

    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://127.0.0.1:5000/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for MLflow server
        run: |
          echo "Waiting for MLflow to be ready..."
          for i in {1..30}; do
            curl -s http://127.0.0.1:5000/ && break
            sleep 2
          done

      - name: Run tests
        run: pytest -v
