name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./src

    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow:2.9.1
        options: >-
          --entrypoint "mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest scikit-learn pandas mlflow flask

      - name: Wait for MLflow server
        run: |
          echo "Waiting for MLflow to be ready..."
          for i in {1..30}; do
            curl -s http://mlflow:5000/ && break
            sleep 2
          done

      - name: Run training script
        run: |
          python src/train.py

      - name: Run tests
        run: |
          pytest -v tests
